### ISSUE TITLE
Email & Password field values are lost when you select a user role from dropdown menu

### ISSUE THREAD

**Issue by grvk** [payloadcms/payload-3.0-demo#115]
# Env

- Reproducible on the latest commit (`6e7f241ce0c9a1e574359bcd94ab1fe6bce264b8`)

# Steps to Reproduce

1. Clone the repo
2. Upgrade payload libs to `beta.11`: 
[package.json](https://github.com/payloadcms/payload-3.0-demo/files/14984414/package.json)
3. `npm install`
4. Update `Users` collection in `payload.config.ts` to include two extra fields: `role` and `fullName` (also update `onInit` function):
<img width="1206" alt="Screenshot 2024-04-15 at 3 20 55 PM" src="https://github.com/payloadcms/payload-3.0-demo/assets/4755076/8d964f99-e2bc-4bad-8eba-3cb34030f4da">
<img width="933" alt="Screenshot 2024-04-15 at 3 21 04 PM" src="https://github.com/payloadcms/payload-3.0-demo/assets/4755076/880f647e-ef0d-4ad3-b632-378c445e84cc">
[payload.config.ts.txt](https://github.com/payloadcms/payload-3.0-demo/files/14984425/payload.config.ts.txt)
5. `npm run dev`
6. Log in to the admin console
7. Select Users Collection
8. Click on `New`
9. Input new user's email and passwords
10. Proceed to selecting `admin` role

# Expected Result
1. Email, password fields preserve values
2. `admin` role is selected

# Actual Result
The moment `admin` role is selected, email and password values get deleted

# Recording
https://github.com/payloadcms/payload-3.0-demo/assets/4755076/83eb3171-f9e6-47e4-a451-2be1b24d182f

**Comment by jmikrut** [comment]
Hey @grvk I believe this is now fixed in the beta which will be releasing in the next few hours. If it persists, we will re-open!

**Comment by grvk** [comment]
@jmikrut 
I just tried the latest version, and the iss
ue seems to be partially there:

https://github.com/payloadcms/payload-3.0-demo/assets/4755076/09d16fe9-e616-4872-a0d8-cd2ffafac0c6

**Comment by jmikrut** [comment]
@paulpopus we need to make sure that we keep the confirm password field state within the `form-state` endpoint, and this will fix the issue.

**Comment by denolfe** [comment]
Ensure your user collection has `auth: true` set on it. Code has been added to warn you if this is not the case.

**Comment by grvk** [comment]
@denolfe @jmikrut 

This issue is still present, unfortunately. 
I checked out the last version of the code:

<img width="916" alt="Screenshot 2024-05-01 at 6 59 48 PM" src="https://github.com/payloadcms/payload-3.0-demo/assets/4755076/2d884de5-3e1b-4083-86bb-db8563e2a3b3">

**Steps to reproduce:**
1. `git clone ...`
2. `npm install
3. Update the files per specs above (just add `role` and `fullName` to `Users`, keep `auth: true`)
4. `rm payload-types.ts` because it was throwing an error (?)
<img width="819" alt="Screenshot 2024-05-01 at 7 01 28 PM" src="https://github.com/payloadcms/payload-3.0-demo/assets/4755076/f8e39292-b032-48a5-85e0-4d93496a0e38">
5. Use the `payload.config.ts` below: 
[payload.config.ts.txt](https://github.com/payloadcms/payload-3.0-demo/files/15182695/payload.config.ts.txt)
6. Start up local PostgreSQL server (16.2)
7. `npm run dev`

The bug is still there (`Confirm Password` field is getting emptied):

https://github.com/payloadcms/payload-3.0-demo/assets/4755076/fe4858e8-aaba-4e9b-b4f3-f929f0878bb3

**Comment by paulpopus** [comment]
Hey @grvk thanks for your reproduction steps here, are you testing this against the latest version of Payload packages `3.0.0-beta.21`?

I've failed to reproduce your bug on this version, if you do still see it would you be able to put your code in a repo so we can check out the exact configuration please?

**Comment by grvk** [comment]
HI @paulpopus 

Here's the recording in better quality:

https://github.com/payloadcms/payload-3.0-demo/assets/4755076/526f383c-29ed-401f-bdd7-37a3aeb019c8

To answer your question: yes, I created a new repo with the latest version (`3.0.0-beta.21`):
<img width="590" alt="Screenshot 2024-05-01 at 8 35 41 PM" src="https://github.com/payloadcms/payload-3.0-demo/assets/99770650/f7cfe3ef-f033-4d73-8212-e1d2edc2177a">

Please find the code here: https://github.com/grvk/payloadcms-pwd-bug

**Comment by george-revkov-spokeo** [comment]
My node version is: `v18.20.2`

**Comment by paulpopus** [comment]
This should be fixed as of beta 24

**Comment by RiteshMRI** [comment]
Hii, Payload Team, 

I am facing some issues regarding to the password while creating new user in Payload.  

1) When I enter email and leave the New Password & Confirm Password fields blank, it will show an validation error on "Confirm Password" field rather than showing it on "New Password" field. This issue is mentioned as shown in below screenshot.

![user_bug_screenshot1](https://github.com/user-attachments/assets/e32d9837-7844-4535-8aef-43ccc858c10b)

2) Once I enter password in New Password field and again leave the Confirm Password field blank and click on "save" button as shown in below screenshot 1 , at that time it will save the user instead of showing the validation message regarding to password comparison. And it will show "user successfully created." as shown in below screenshot 2.

![user_bug_screenshot2](https://github.com/user-attachments/assets/253c5bb8-089f-48bc-a32c-12d141effe7c)
![user_bug_screenshot3](https://github.com/user-attachments/assets/b2954cde-c61e-435d-8eca-d87a66121574)
